### ISSUE TITLE
[US-002] Pantalla Inicio [Para Regresión]

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#12]
**User Story**

_Como cliente, quiero ver una variedad de platos disponibles en la pantalla de inicio para tener una idea rápida de las opciones de comida ofrecidas y decidir qué quiero ordenar._

Criterios de Aceptación:

1. Al abrir la aplicación de comida, se debe mostrar una selección de platos en la pantalla de inicio, presentada de manera atractiva y fácil de explorar para el usuario.
2. Cada plato en la selección debe incluir una imagen representativa, el nombre del plato, detalles del restaurante que lo prepara y su precio.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/0ffebd15-8051-43da-ade0-9c595d640816)

**Comment by MAITAYORMARIS** [comment]
Se ajustó el diseño de la tarjeta de producto al diseño en alta.

Falta ajustar:
 -Navbar al nuevo diseño, ajustando disposicion de elementos y colores
- Footer: paginas definitivas a enlazar y asignar clases para marcar como activo segun la pantalla en la que se encuentre el usuario

**Comment by FedeBazan** [comment]
@MAITAYORMARIS 


![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/88d3073a-b476-483a-9a1d-c3a11cff80a2)

<h1>Defectos</h1>
<ul>
<li>Header de inicio distinto</li>
<li>"Retiro del local" es la opción de la derecha</li>
<li>No se presenta "Envío a domicilio", esta "Delivery"</li>
<li>Los elementos del Footer deben ser: Inicio, Descuentos, Mi pedido y Cuenta</li>
<li>Uso de otro color del footer, se usa #606060 y debe ser #292929</li>
</ul><br>
<i>Carta regresada a "In Progress"</i>

**Comment by FedeBazan** [comment]
otra diferencia es que los precios se muestran en "Enteros" mientras que en el prototipo se muestra con decimales.

**Comment by MAITAYORMARIS** [comment]
Verificaré las observaciones.

Navbar y footer los trabajo hoy, ya que en alta se modificó su uso general en toda la app.

Consultaré el tema de los montos como se va a manejar porque así viene de la API.

**Comment by MAITAYORMARIS** [comment]
Ajustados los estilos segun figma en alta. 

La navegacion de volver atrás en el navbar desde otras pantallas queda sujeta a modificacion según definicion del equipo y posibles pantallas adicionales

**Comment by FedeBazan** [comment]
Se generaron Tickets de reportes.
Espacio blanco en la derecha #61 
Elementos Header/Footer se ocultan al navegar #62

**Comment by FedeBazan** [comment]
Tarjeta Movida a In Progress, al resolver los tickets indicados se debe regresar a Testing para corroborar los bugs resueltos

**Comment by FedeBazan** [comment]
VISUAL [OK] A confirmar por documentación los productos del Inicio
FUNCIONAL [REGRESIÓN]

**Comment by MAITAYORMARIS** [comment]
La vista ya esta configurada para consumir datos de la API.

Agregaré un spinner de carga solo como efecto visual, para cuando se realiza la conexion y se espera la respuesta.

**Comment by MAITAYORMARIS** [comment]
Nota: Esta vista ya tenía aprobación visual.
En caso de haber nuevos detalles visuales, no me encargaré de corregirlos, ya que los cambios post-aprobacion han sido aplicados por otros desarrolladores.
