### ISSUE TITLE
[US-006] Confirmación Pedido [Para Regresión]

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#15]
**User Story**

_Como cliente, quiero poder revisar y confirmar mi pedido desde la pantalla de resumen antes de proceder al pago, para asegurarme de que todos los detalles sean correctos antes de finalizar la compra._

Criterios de aceptación:

1. El usuario debe poder acceder a una pantalla de resumen que muestre todos los productos seleccionados junto con sus cantidades, precios individuales, costo del envío si corresponde y el precio total del pedido.
2. Se debe incluir un botón para Pagar en la pantalla de resumen, que permita al usuario proceder al pago una vez que esté satisfecho con los detalles del pedido.
3. Se debe proporcionar una opción clara para que el usuario pueda regresar a la pantalla anterior para realizar ajustes adicionales en el pedido, si así lo desea, sin perder los productos seleccionados.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/85b326f0-7355-4135-a1f1-b8db1b04fb29)

**Comment by Mauroariza** [comment]
1. Inicio con la identificación de lo que necesito para su realización, también con la relación que existen entre las otras vistas y su conexión existente con los datos que seleccionó el cliente.

**Comment by Mauroariza** [comment]
2. Dentro de lo analizado veo que hay una relación directa entre los datos que serán pasados desde producto elegido a confirmación pedido. En ese caso la lógica que debería usarse desde la vista ( producto elegido) y confirmación pedido es la del estado global. Esto porque los datos: del producto, de la dirección del restaurante y de la  de la cantidad serán necesitados.

**Comment by Mauroariza** [comment]
3. No había una página como tal para confirmar producto, así que creé una llamada ConfirmOrders, el propósito de esta es poder ser accedida de forma privada por el usuario. Así el usuario será redireccionado a esta ruta en el momento que tenga un producto elegido y ya haya iniciado sesión. 
4. Habría que ver cómo esta página será privada, por un lado debería existir la autenticación y por otro lado es importante que en el carrito de compras existan productos activos, de esa forma sí se puede confirmar la compra.

**Comment by Mauroariza** [comment]
5. Moví a testing. Está en la ruta /confirmacion,  por ahora solo renderiza los datos de forma estática.

**Comment by MAITAYORMARIS** [comment]
El elemento se encuentra construido en baja.

A partir de ahora lo ajusto al diseño ya disponible para su vista en alta ajustando maquetacion y estilos

**Comment by FedeBazan** [comment]
@MAITAYORMARIS La vista d ela tarjeta fue actualizada - Tarjeta regresada al Backlog

**Comment by FedeBazan** [comment]
No arrastra el pedido hecho. se visualiza que se pide una "hamburguesa clásica" para cualquier pedido X
