### ISSUE TITLE
[US-012] Final Exitoso [Para regresión]

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#19]
**User Story**

_Como cliente, quiero recibir una notificación de entrega exitosa una vez que mi pedido haya sido entregado satisfactoriamente, para confirmar que he recibido mi comida y que el proceso de entrega ha sido completado con éxito._

Criterios de aceptación:

1. Después de que se entregue el pedido, se debe enviar una notificación al usuario informando sobre la entrega exitosa.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/4c7f5ad0-dce7-4918-b0af-199fb0c85666)

**Comment by FedeBazan** [comment]
Especificar link de la vista, asegurarse de que este subido a la rama DEV.

**Comment by k-alex-leon** [comment]
Ruta del view: http://localhost:5173/busqueda/pagar/final-exitoso

**Comment by k-alex-leon** [comment]
View actualizada : http://localhost:5173/busqueda/pagar/final-exitoso

**Comment by FedeBazan** [comment]
No es posible visualizar la vista desde el link : http://localhost:5173/busqueda/pagar/final-exitoso



https://github.com/No-Country/s14-16-n-java/assets/48597230/3378e3cf-21cf-483d-82d8-74849f998a1f

Movido a In Progress

**Comment by FedeBazan** [comment]
Movido para Regresión.

**Comment by FedeBazan** [comment]
No es posible visualizar, coordinar con @Wlfernando US011 no redirecciona a las páginas siguientes.
