### ISSUE TITLE
[US-013] Compensación

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#20]
**User Story**

_Como cliente, quiero recibir una compensación adecuada si mi pedido no es correcto o si llega con un retraso significativo, para garantizar una experiencia satisfactoria._

Criterios de aceptación:

1. Se debe poder seleccionar claramente la causa del reclamo.
2. La compensación puede incluir una variedad de opciones, como el envío del pedido correcto más un regalo, un cupón de descuento para futuras compras y la devolución del dinero.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/5ac0d102-4303-4be0-ba40-ff7886a9c31f)

**Comment by FedeBazan** [comment]
Especificar link de la vista, asegurarse de que este subido a la rama DEV.

**Comment by k-alex-leon** [comment]
Ruta del view : http://localhost:5173/busqueda/pagar/compensacion

**Comment by FedeBazan** [comment]
Prototipo en evaluación se reserva test hasta entonces

**Comment by k-alex-leon** [comment]
View actualizada: http://localhost:5173/busqueda/pagar/compensacion

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/03066ec7-d65b-4e2d-b656-e8b702c6a2bd)

Texto incorrecto, "Pedido correcto más otro producto de regalo"

Movido a In progress

**Comment by k-alex-leon** [comment]
Cambios realizados: http://localhost:5173/busqueda/pagar/compensacion

**Comment by FedeBazan** [comment]
Coordinar con @k-alex-leon [US-016] , queda sin acción el usuario y vercel,dev,devdos se traban en esta visual, conflictúa el resto de vistas posteriores.
