### ISSUE TITLE
[US-014] Final con reclamo

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#21]
**User Story**

_Como cliente, quiero recibir un mensaje de confirmación después de realizar un reclamo sobre un pedido incorrecto o con retraso, para tener la tranquilidad de que mi problema ha sido registrado y será atendido adecuadamente._

Criterios de aceptación:

1. Después de que un usuario haya realizado un reclamo sobre un pedido incorrecto o con retraso, se debe enviar un mensaje de confirmación para informar al usuario que su reclamo ha sido recibido.
2. El mensaje de confirmación debe transmitir empatía y comprensión hacia el usuario, reconociendo el inconveniente experimentado y expresando el compromiso de la empresa para resolver el problema de manera satisfactoria.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/10180765-5780-48f0-a9d1-9910dd39e40f)

**Comment by FedeBazan** [comment]
Especificar link de la vista, asegurarse de que este subido a la rama DEV.

**Comment by k-alex-leon** [comment]
Ruta del view: http://localhost:5173/busqueda/pagar/final-con-reclamo

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/2d877d8c-a217-41b1-9a35-d9e7273b680d)

Texto marcado debe estar en mayúsculas

**Comment by k-alex-leon** [comment]
View actualizada: http://localhost:5173/busqueda/pagar/final-con-reclamo

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/b42e14b4-da22-4e82-bd64-b251b5ad57c8)

"para ello" no se encuentra presente en el prototipo.

**Comment by k-alex-leon** [comment]
Cambios realizados: http://localhost:5173/busqueda/pagar/final-con-reclamo

**Comment by FedeBazan** [comment]
Coordinar con @Wlfernando [US-011] , queda sin acción el usuario y vercel,dev,devdos se traban en esta visual, conflictúa el resto de vistas posteriores.
