### ISSUE TITLE
[US-007] Medio de Pago

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#23]
**User Story**

_Como cliente, quiero poder seleccionar el método de pago que prefiera al finalizar mi compra, para realizar transacciones de manera conveniente y segura._

Criterios de aceptación:

1. El usuario debe ser dirigido a una pantalla de selección de medios de pago donde pueda elegir entre diferentes opciones de pago.
2. Se deben ofrecer múltiples medios de pago, como pago online y en efectivo.
3. Para cada método de pago disponible, se deben proporcionar instrucciones claras sobre cómo completar la transacción.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/208b4ef6-9a19-4fa8-8c03-1853c87d4eef)

**Comment by k-alex-leon** [comment]
View completado, los datos permaneces estáticos

**Comment by FedeBazan** [comment]
Especificar link de la vista, asegurarse de que este subido a la rama DEV.

**Comment by k-alex-leon** [comment]
Link del view : http://localhost:5173/busqueda/pagar/medio-de-pago

**Comment by FedeBazan** [comment]
Test en reserva por el prototipo

**Comment by k-alex-leon** [comment]
View actualizada: http://localhost:5173/busqueda/pagar/medio-de-pago

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/1c94c26f-d902-4dd1-8786-6ca8119d1807)

El texto marcado debe aparecer en un solo renglón.
Vista 360x640
Movido a "In Progress"

**Comment by k-alex-leon** [comment]
Cambios realizados: http://localhost:5173/busqueda/pagar/medio-de-pago

**Comment by FedeBazan** [comment]
arrastra precio errroneo del pedido, coordinar con equipo.
