### ISSUE TITLE
[US-005] Producto Elegido - Detalles del plato

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#33]
**User Story**

_Como cliente, quiero ver información detallada de cada plato, incluyendo ingredientes y alérgenos._

Criterios de aceptación:

1. La información debe ser precisa, completa y actualizada.
2. Se debe indicar claramente la presencia de alérgenos en cada plato.
3. Se debe ofrecer la posibilidad de realizar modificaciones a los platos.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/84d6534c-0da1-4489-a174-cbc5fe646f10)

http://localhost:5173/busqueda/pagar/producto-elegido

**Comment by FedeBazan** [comment]
[https://github.com/orgs/No-Country/projects/115/views/2?pane=issue&itemId=58680878](url)

**Comment by FedeBazan** [comment]
Confirmar link de acceso, no se visualiza. Asegurarse que los cambios estén subidos en la rama Dev.

**Comment by MiltonOscarFlores** [comment]
Reparado link de acceso , ya deberia poder visualizarse la vista, faltaba mergear mi rama feature con la rama Dev. 
Hecho.

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/26213c35-9de8-4793-9e87-66144b8bfe2d)

**Comment by FedeBazan** [comment]
No son funcionales los botones de ingredientes y aclaraciones
