### ISSUE TITLE
[US-016] Aviso de llegada - Cartel de entrega

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#34]
**User Story**

_Como cliente, quiero recibir un aviso cuando mi pedido haya sido entregado, para estar informado sobre el estado de mi pedido y poder recibirlo en el momento adecuado._

Criterios de aceptación:

1. Una vez que mi pedido haya sido entregado, quiero recibir una notificación de confirmación de entrega.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/3a495202-7a8c-4426-bedb-0a57ad5cd07b)

**Comment by k-alex-leon** [comment]
View actualizada: http://localhost:5173/busqueda/pagar/aviso-de-llegada

**Comment by FedeBazan** [comment]
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/c337de16-3226-4cde-8d63-e23db2fce07a)

"-Negrita de texto muy fuerte
-Color de la parte inferior incorrecto"

**Comment by k-alex-leon** [comment]
Cambios realizados: http://localhost:5173/busqueda/pagar/aviso-de-llegada

**Comment by FedeBazan** [comment]
Coordinar con @Wlfernando [US-011] , queda sin acción el usuario y vercel,dev,devdos se traban en esta visual, conflictúa el resto de vistas posteriores.
