### ISSUE TITLE
[US-017] - Aviso de llegada - Reclamo

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#35]
**User Story**

_Como cliente, quiero poder realizar un reclamo si mi pedido no es correcto, para que el proveedor pueda corregirlo rápidamente y asegurar una experiencia satisfactoria para mí y otros clientes._

Criterios de aceptación:

1. Debe proporcionar una opción para seleccionar si el pedido cumple con las condiciones adecuadas o si necesito iniciar un reclamo.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/94768f67-2597-41bb-9e8d-6fd4de3b08b8)

**Comment by k-alex-leon** [comment]
View actualizada: http://localhost:5173/busqueda/pagar/aviso-de-llegada

**Comment by FedeBazan** [comment]
La correción del color inferior se especifico en US-016
Movido para Regresión

**Comment by FedeBazan** [comment]
Coordinar con @Wlfernando [US-011] , queda sin acción el usuario y vercel,dev,devdos se traban en esta visual, conflictúa el resto de vistas posteriores.
