### ISSUE TITLE
TEST CONEXIÓN ENTRE VISTAS JUEVES 20Hs. ARG (3° Sprint)

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#46]

**Comment by MAITAYORMARIS** [comment]
Se enlazaron las vistas desde inicio
-> elegir un producto> 
      detalle de producto>
            confirmar(esta vista no está implementada aun, sigue el camino con el boton pagar)>
               ingresar monto>hacer pedido (va al detalle de pedido), quiero agregar (vuelve al inicio)>
                 pago realizado con exito (aceptar va a detalle de entrega)

Detalle de entrega es la vista final por ahora hasta tener la vista de aviso de llegada con las opciones si/no
