### ISSUE TITLE
[REPORT] US-002 : Espacio Blanco en la derecha

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#61]
Reportado Por: @FedeBazan 
Dev a cargo: @MAITAYORMARIS 
Fecha del Reporte: 14/04/2024
Ambiente: Desktop (Run emu mobile screen)
Sistema Operativo: Windows 10
Estado: Abierto
Descripción: La web no se acomoda correctamente a la dimensión de 360x640
Pasos para la producción:

  1. Abrir la pagina web ( http://localhost:5173/inicio)
  2. Activar herramientas de desarrollador de navegador
  3. Hacer Scroll en los costados

Resultado Actual: Se presenta un espacio blanco en la derecha.

Resultado Esperado: La página debe adaptarse correctamente en la dimensión 360x640.

Observación: Este espacio en blanco se presenta en los siguientes navegadores (emulación responsive 360x640)

  - Opera GX
  - Chrome
  - Mirosoft Edge

Archivo Adjunto(Foto, Video):

Chrome:
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/a23203e7-9bf7-476d-8bbc-f5cb539a66e5)

Opera GX:
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/8b1eea0d-ea3f-4100-94d5-72dde0fb80bf)

Edge:
![Image](https://github.com/No-Country/s14-16-n-java/assets/48597230/f5438802-2293-4fc6-b145-db71c7414eb4)

**Comment by MAITAYORMARIS** [comment]
corregido scroll horizontal

**Comment by FedeBazan** [comment]
NO USAR MICROSOFT EDGE PARA PRESENTACIóN.
