### ISSUE TITLE
[REPORT] US-002 : Elementos Header/Footer se ocultan al navegar

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#62]
Reportado Por: @FedeBazan 
Dev a cargo: @MAITAYORMARIS 
Fecha del Reporte: 14/04/2024
Ambiente: Desktop (Run emu mobile screen)
Sistema Operativo: Windows 10
Estado: Abierto
Descripción: Al navegar haciendo scroll para arriba y abajo, los elementos Header y Footer se ocultan parcialmente y no son completamente visibles.
Pasos para la producción:

  1. Abrir la pagina web ( http://localhost:5173/inicio)
  2. Activar herramientas de desarrollador de navegador
  3. Hacer Scroll arriba y abajo

Resultado Actual: Header/Footer no son completamente visibles en la navegación.

Resultado Esperado: Header/Footer deben poder ser visibles mientras se navega en las vistas que pertenecen.

Observación: este problema se encuentra presente en todos los navegadores.

Archivo adjunto:

https://github.com/No-Country/s14-16-n-java/assets/48597230/f2fab624-6215-44c8-a486-b3690fff197e

**Comment by MAITAYORMARIS** [comment]
Corregida la visualizacion en vista Home y Confirmacion de Pedido.

A tener en cuenta, el desplazamiento de navbar y footer se puede generar por algun elemento dentro del cuerpo de la vista que se encuentre con desbordamiento.
