### ISSUE TITLE
[US-018] Detalles del pedido

### ISSUE THREAD

**Issue by FedeBazan** [No-Country/s14-16-n-java#65]
**User Story**

_Como cliente, quiero poder ver los detalles de mi pedido, para corroborar que todo está correcto antes de que sea enviado._

Criterios de aceptación:

   1. En la pantalla "Detalles del pedido", se debe mostrar la información del restaurante, y los datos de mi pedido incluyendo el nombre del plato, el precio individual, el costo del envío, el total a pagar, cómo será el pago y el tiempo estimado de entrega.
   2. Al hacer click en el botón "Hacer el pedido" redirige a la pantalla de procesamiento del pago.

![Image](https://github.com/No-Country/s14-16-n-java/assets/88388043/ddfe72db-861b-4d62-9c3d-79fcca89bd52)

ruta: busqueda/pagar/detalle-de-pedido

**Comment by MAITAYORMARIS** [comment]
La vista ya tiene la estructura de diseño en alta de figma.

Actualmente, consume datos de prueba, para agregar funcionalidad requiere obtener los datos generados en la vista anterior, cuando la lógica de esa vista previa esté realizada se podrá obtener los datos y generar la funcionalidad REAL

Nota: Se debe reincoporar a las rutas en la aplicación para poder visualizar su contenido, fue eliminada con la ultima actualizacion realizada en el anidamiento de rutas.

**Comment by FedeBazan** [comment]
Vista no visible
[Vercel] X
[Dev] X
[devDos] X

**Comment by MAITAYORMARIS** [comment]
> Vista no visible [Vercel] X [Dev] X [devDos] X

La vista fue finalizada y agregada a la navegacion el 16/04  commit:4a70ffdc5eb11416e162c15fdd862470c3ff98a5
posteriormente en actualizaciones fue eliminada el 17/04 commit 4a70ffdc5eb11416e162c15fdd862470c3ff98a5
esto fue notificado para corregir la navegacion en discord


Capture de visualizacion en local: https://drive.google.com/file/d/18axXgr2jJU_ivdy3AZ-0JW0G9EQBQeRt/view?usp=sharing

Tras nuevos commits posiblemente se haya eliminado el enrutado.
Ya no colaboro en el manejo de la navegacion, este proceso y ajustes de estilos posteriores a la aprobación de vistas esta a cargo de los lideres de equipo front

**Comment by FedeBazan** [comment]
@Wlfernando Espero la confirmación de si esta vista debe ser visible.
